FROM gcr.io/distroless/static-debian13:nonroot

ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

COPY --chown=nonroot:nonroot ${TARGETOS}/${TARGETARCH}${TARGETVARIANT:+/$TARGETVARIANT}/proxyaudit /usr/bin/proxyaudit

ENTRYPOINT ["/usr/bin/proxyaudit"]
